# Generated by Django 5.0.6 on 2024-06-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DOC_PENDING', 'Document Pending'), ('DOC_VERIFIED', 'Document Verified'), ('CONTRACT_PENDING', 'Contract Pending'), ('PRINT_PENDING', 'Print Pending'), ('FINALIZED', 'Finalized')], default='PENDING', max_length=25),
        ),
    ]
